### ISSUE TITLE
Gentoo Linux Issue - Xbox 360 Controller Not Detected

### ISSUE THREAD

**Issue by bunder2015** [KernelZechs/open-joystick-display#17]
Hello, I'm not sure if this is something on my end, but for some reason OJD doesn't detect my 360 controller on linux. edit: I'm using the in-kernel xpad driver.

```
[23737304.830392] usb 1-11: new full-speed USB device number 10 using xhci_hcd
[23737304.961336] usb 1-11: New USB device found, idVendor=045e, idProduct=028e, bcdDevice= 1.14
[23737304.961338] usb 1-11: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[23737304.961339] usb 1-11: Product: Controller
[23737304.961340] usb 1-11: Manufacturer: ©Microsoft Corporation
[23737304.961341] usb 1-11: SerialNumber: 17578B5
[23737304.963849] input: Microsoft X-Box 360 pad as /devices/pci0000:00/0000:00:14.0/usb1/1-11/1-11:1.0/input/input24
```

The controller seems to work in steam and steam games but OJD doesn't even see it.  I also tried a web-based controller display and it seemed to have the same problem, so this could be my fault.  If you need more information, let me know.

Thanks

**Comment by KernelZechs** [comment]
@bunder2015 My 360 controller and Linux is my primary work environments so I do know for a fact they work. It appears from your dmesg log that you are using USB and it doesn't look like the dongle and it looks like it has loaded. So that leaves me to believe that it could be user group permission issues (since you say it doesn't work in chromium or firefox), the version of Linux you are running, or something to do with a hardware subsystem (hal, dbus, systemd garbage). So if you could provide me the following:

1. What distro are you using
2. Version of the distro
3. The kernel you are running
4. List of groups your user belongs to.

That way I can replicate your environment and get back to you.

Thanks!

**Comment by KernelZechs** [comment]
Also, If you are running arch or gentoo I need to know the install process you followed because they are 'build as you want' distros I need to replicate down to what you decided to install and not install so I can effectively replicate this environment.

**Comment by bunder2015** [comment]
Thanks for getting back to me.  I am actually using gentoo (rolling), with kernel 4.19.0 (I can upgrade to 4.19.66 if it helps).  I don't use systemd, but I am using openrc+eudev.

```
uid=1000(chris) gid=100(users) groups=100(users),10(wheel),18(audio),27(video),85(usb),78(kvm),102(libvirt),35(games)
```

Now that you mention it, I'm not in the input group.  Let me try that and get back to you.

Thanks again

**Comment by bunder2015** [comment]
No dice unfortunately.  I just noticed I don't have /dev/js0 either.  Maybe that's the problem.  I'll keep poking around.

Thanks again

**Comment by KernelZechs** [comment]
In the meantime, can you provide a dump of your kernel config so I can spend some time spinning this up. I needed to build a gentoo environment anyways.

**Comment by bunder2015** [comment]
Sure no problem.

https://gist.github.com/bunder2015/7fc7c37ab794c14148d59ecd51ba0aeb

**Comment by bunder2015** [comment]
Okay, I enabled CONFIG_INPUT_JOYDEV and its working now.  How steam worked without it this whole time I don't know.  Sorry for the trouble.

**Comment by KernelZechs** [comment]
Good to know, thanks for looking into it.
