### ISSUE TITLE
Fight Sticks - Fix layout

### ISSUE THREAD

**Issue by Formedras** [KernelZechs/open-joystick-display#19]
The "Xbox ABXY" and "PlayStation XOST" fightstick layouts are incorrect: The L and R positions are switched. Bottom row (Xbox notation) should be A, B, RT, LT, and top row should be X, Y, RB, LB.

Sticks with this layout are designed with Street Fighter in mind, and PlayStation and Xbox 360/One default control schemes put Heavy Punch and Heavy Kick on R1/R2, not L1/L2.

**Comment by KernelZechs** [comment]
@Formedras you can build your own theme here using this guide: https://ojdproject.com/developer-guide. 

I built these off various board templates that my friends use for their various platforms for DBFZ and BB. If they don't work for you, you can build / modify your own template. since every fight stick configuration is different for whoever uses it.  I cannot take into account all the different variations of arcade and fight sticks, you will need to do some work to theme it the way you want the layout to be. 

I suggest using Inkscape to make your theme. If you need help let me know, in the meantime this isn't a bug and I'm closing this ticket.
