### ISSUE TITLE
Feature request: Hidden output window for streaming

### ISSUE THREAD

**Issue by elfchief** [KernelZechs/open-joystick-display#23]
I have a Tobii eye tracker, and one of the things that it has (for Windows, at least) is their "ghost" software, for interfacing with streaming and such. One of the ways it does that is providing a window with a "where I'm looking" marker on it, which can then be captured with OBS and overlaid onto my stream.

The useful parts: That window is completely hidden from the user (OBS can see it,, but it otherwise doesn't exist), *and* the window capture has alpha included in it, so chromakey isn't required (I'm assuming one couldn't do that for a normal window). When Ghost is running normally, it's just a tasktray icon and that's it.

Anyhow, it would be really awesome if OJD offered a mode like this, where the normal mode has no visible windows, but the config interface could be brought up as a separate window when needed (added bonus: that would let you change your config without having the whole config interface potentially visible to someone's stream).

**Comment by KernelZechs** [comment]
Hey @elfchief,

Thanks for making a recommendation, unfortunately there are two hurdles I would need to get over to make this work one of which is outside of my control.

- Add browserwindow support to OJD (which would give you your invisible window, however I dislike it because this option isn't really available for Linux users in OBS).
- Chromium/Electron needs the window to accept button presses as well as allowing OBS to render it. (This is a problem with Electron and Chrome)

Since my goal is ease of use, compatibility, and portability across all operating systems that feature is out of the question for now. Maybe in the future if I decide to leave electron (and it has been a consideration for something like C/SDL which would also be cross platform and more performant) I'll add it in as a feature.

Anyways, thanks again. Let me know if you have anything else you'd like to see. I'm still working on a rewrite with new features and interface, just taking longer than I hoped because of real life stuff.
