### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by Hepsily** [KernelZechs/open-joystick-display#24]
First of all I just want to say its a really cool program.
I would like to be able to out put the information to a physical device, so when a button is pressed or a joystick moved it controls lights and movement, so you are controlling both a game and a physical device at the same time, any ideas how I could add some code to output to an Ardunio or other such device?
Thanks!

**Comment by KernelZechs** [comment]
Good Morning Hepsily,

For the PC controller stuff I'm using this:
https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API

If you're looking to write some special software that interacts with an arduino, such as a robot, a TAS, or the like, I would suggest looking into the serialport.io NodeJS Library (https://serialport.io). I use this library for the RetroSpy integration with various consoles and allows for general serial communication.

However, I don't know if I would use OJD for this since it's really the other way around (takes input doesn't output), I would start a clean project and experiment with the API stuff above. Here is a tutorial on how to start an electron project.

https://electronjs.org/docs/tutorial/first-app

I recommend using the latest version of NodeJS and using `yarn` as your package manager. Furthermore, I recommend any development stuff you do in linux/mac and then port it over to windows to help save you development headaches (firm believer *nix is easier to do development work in, but that is your call.)

I hope this helps you with your project. Would love to see the final result, I have an arduino as well and always interested in seeing what others come up with. 

Also, If you can make it in a way that would benefit more than just one device I could see it being merged into the OJD codebase, so think in more generic terms when developing your feature.

Take it easy!
