### ISSUE TITLE
Full RetroSpy Support

### ISSUE THREAD

**Issue by edru** [KernelZechs/open-joystick-display#25]
Recently found this application, and that it supported RetroSpy. Would love to see this get full RetroSpy Support so it supported all controllers from its main application.

I also noticed that there was support for the RetroSpy Genesis, but not profile mapping to select for it.

**Comment by KernelZechs** [comment]
@edru Mostly because I don't have a Genesis/MD, or a TG16, or various other consoles, the ones I have mappings for are the ones I tested (ones I don't I did the literal driver translation). If you have said consoles and want to help implement with me that would be great.  Just make a new mapping and send me your config.json and I can add it to the next release. If it doesn't work I can help you work through that as well.

**Comment by edru** [comment]
Sounds good. I'll see what I can brew up as needed and submit them.

**Comment by KernelZechs** [comment]
I'm going to close this ticket out, if you have anything to share please just comment back on this ticke and I'll reopen it. Thanks!
