### ISSUE TITLE
[Feature request] Triggers on Xbox One controller not detected as axis

### ISSUE THREAD

**Issue by hydargos123** [KernelZechs/open-joystick-display#33]
Hello,
This software is really great, I have not used it in a stream but I sure will.

I am using an Xbox One S Controller, and the triggers (L2 and R2) do not appear as axis, even though they are analog and are detected as such in different gamepad testers. On OJD, they just appears as button (6 & 7) and light up when pressed lightly, and no axis appear in the axis viewers.

It would be really great to have a way to visualize how much the triggers are pressed (by lighting the buttons gradually for example), as it can be interesting to show in some games, like racing games.

Have a great day
hydargos

**Comment by KernelZechs** [comment]
@hydargos123 Unfortunately I have no way to fix this right now, this is in relation to how chromium interprets the inputs, you can even visualize this yourself (using chrome) on this website: https://html5gamepad.com/ (Tested using a XBO controller). 

Ironically, the latest feature I added, racing wheels, the Logitech G pedals work on an axis and do show actuation has you're describing above. However the Xbox controller doesn't work.

I have been noodling around with a raw HID alternative to the chromium driver for awhile to work around these silly limitations of the core framework, but I've had operating system incompatibilities and I refuse to do any feature that won't work on all systems seamlessly. Because of this, it has been put on the back-burner until after OJD 3.0 is released.

I will get back to it eventually as I do want raw operating system gamepad interaction since it will help with compatibility and features going forward.

Sorry I can't be of help now, but I hope to have this feature in sometime this year after OJD 3.0 is released.

Thanks.

**Comment by hydargos123** [comment]
Hello,

I suspected an incompatibility issue, so no big surprise. I didn't think of testing on a Chromium browser, I only tested this website with Firefox, so that makes more sense.
No problem, this is not a necessary feature for me, it works fine without it.

Have a great day
