### ISSUE TITLE
Enhancement: PS4 SCUF Theme Suite

### ISSUE THREAD

**Issue by seathasky** [KernelZechs/open-joystick-display#38]
Hi there! I've read your theme guide extensively and it is beyond me. lol. I just wanted to know if it's possible to have a theme available or if someone could make me one that showed Scuf controllers inputs as well as the standard Playstation controller that is defaulted with your program.
So basically, it would show the paddle inputs to the side or something as well as the regular Playstation inputs.
I'm sure it would be straight forward for someone who actually knew what they were doing.

Back:
https://user-images.githubusercontent.com/46404303/62379909-ec9a8100-b515-11e9-9d97-22f9f8bbd6d3.png

Front: 
https://scufgaming.com/media/wysiwyg/apex/hero.jpg

Thanks!

**Comment by seathasky** [comment]
Also, I tried to find the discord mentioned in another post, but could not find an actual link :P

**Comment by KernelZechs** [comment]
@seathasky Give me some time today, I should have it done shortly. I decided that I wasn't just going to do the Apex Legends theme but a suite of controller options as well so other people could enjoy this enhancement as well.

As a rule of thumb, I don't do one-off theme requests unless they can be generalized for lots of people. It just so happens that SCUF has a great controller builder and I was able to make this a theme for everyone with various styles with ease.

**Comment by KernelZechs** [comment]
Download:
[scuf.zip](https://github.com/KernelZechs/open-joystick-display/files/4113612/scuf.zip)

Video:
https://www.youtube.com/watch?v=uDmrA9WNROo&feature=youtu.be

@seathasky here is the SCUF theme I created this morning. This has your Apex Legends configuration in here as well. All you need to do is the following:

- Extract the ZIP
- In OJD on the profile panel select [Select Folder] and point it to the `themes` folder you just extracted.
- In the `theme` select menu select `SCUF Playstation 4`
- In the `style` select menu select `Apex Legends`

You're good to go, the controller uses the following buttons, configure accordingly.
UP, DOWN, LEFT, RIGHT, L, R, L2, R2, L3, R3, CROSS, SQUARE, CIRCLE, TRIANGLE, OPTION, SHARE, START, PS.

This will eventually become a system theme on the next release. Once this is done I will repost to this ticket to let you know to download the latest version of OJD. However you're free to customize this one to your hearts content. Should give you a good idea on how to do your own in the future.

Again, I want to reiterate, I don't do custom themes one-off unless I can find a way for it to benefit the entire application and user base. I'm happy to help you do theme development, but I don't really have time to do single themes for people and I'm not really about doing commissions for such since the time/value proposition isn't there for me. I'm the one and only developer who works on this, keep that in mind for the future.

Furthermore, the discord was closed early last year- I don't plan on resurrecting it. Support channels for this application is github so you came to the right place.

Anyways, I hope you enjoy this theme.

**Comment by seathasky** [comment]
Oh wow! You did it, ty soo much!! This is great! I do appreciate it, I think others can benefit from it too! A lot of streamers use Scuf controllers in Apex!

I hate to sound ungrateful in the end but I was hoping for the mod buttons as well but my dumbbutt put the wrong "Back" screenshot in the original post haha!
I was looking for this to be added as well!
https://scufgaming.com/media/wysiwyg/apex/regularLayout.jpg

 So that's what I meant by paddle inputs. I know you said you dont normally do custom themes, I really wish I would of put the right screenshot the first time, I honestly didnt expect you to do it haha.
Anyways. If not I understand. If you do, well that would be amazing!
Cheers!

**Comment by KernelZechs** [comment]
@seathasky the issue comes down to the fact that everyone's backside mod buttons are different and be reconfigured and since they activate the same buttons that are highlighted on the front (IIRC SCUF controllers do this via a firmware in the controller for console compatibility, correct me if it's wrong) It doesn't add any real value to the controller visualization to show the backside on stream.

**Comment by seathasky** [comment]
I suppose not but it does look funny when you have both thumbs on your sticks and are mashing your buttons lol, thats the only reason I requested this 👍

**Comment by KernelZechs** [comment]
@seathasky Version 2.8.0 is live, this has the SCUF themes built in. Feel free to download it when you feel like it. Thanks!
