### ISSUE TITLE
New Mac Version

### ISSUE THREAD

**Issue by blackholebh** [KernelZechs/open-joystick-display#42]
On Mac OS 10.15 the new zip to app version gives error "cannot be opened," the previous dmg versions all work

**Comment by KernelZechs** [comment]
@blackholebh I need more information since it opens on my MacOS instance just fine. Please read the ticket template below on how to get started. My gut says your issue is with MacOS's walled garden but I can't know for sure until you provide me the exact error message and screenshots.

## For Bug Reports
- Information and version about the operating system you are currently using:
  - For **Microsoft Windows** you can get this information by going to `Command Prompt` and using the `systeminfo` command.
  - For **MacOS** you can find this in your `Apple Menu` > `About`
  - For **Linux** you will need provide the following:
    - Which distro you are currently using?
    - Which version of the distro are you currently on?
    - Which kernel you are using?
    - What desktop environment are you using? (Please include details on the window server such as X11 or Wayland as well)
    - Are you using desktop compositing? (If you don't know, likely yes)
    - Determine if your system is currently up to date.
    - If you're a Gentoo/Arch/Manjaro/Slackware user, a list of installed packages and libraries is required for me to proceed. 
- A detailed description in list format on how to recreate the bug. (Don't hide it in a paragraph of text)
- Screenshots and Videos will speed up resolution time. If you can please, provide them.

**Comment by KernelZechs** [comment]
@blackholebh 

Just in case this is your issue, you can watch the video tutorial below I made, alternatively you can read the documentation link on how to fix it. If this works for you comment back and close the ticket. Thanks

Video:
https://www.youtube.com/watch?v=oHyOLrff4X0&feature=youtu.be

Instructions Are here In The Documentation
https://ojdproject.com/user-guide#install

**Comment by blackholebh** [comment]
<img width="420" alt="Screen Shot 2020-02-15 at 12 18 32 PM" src="https://user-images.githubusercontent.com/46506773/74592243-5deedc80-4fed-11ea-8eb5-107640299fe0.png">
<img width="242" alt="Screen Shot 2020-02-15 at 12 18 42 PM" src="https://user-images.githubusercontent.com/46506773/74592244-5deedc80-4fed-11ea-8042-d7c8e3a9be86.png">

Just downloaded as is doesn't even give the unidentified developer pop up. Probably has to do with me being on beta.

**Comment by KernelZechs** [comment]
Unfortunately I don't support alpha, beta, developer previews, or release candidates of software. Honestly I'm surprised Apple hasn't kicked you out of the beta yet since Catalina was released back in October.

Regardless I'm going to close this ticket. I have verified it has worked on both Catalina and Mojave stable. In the meantime you can use an old build here (https://ojdproject.com/downloads/macos/stable/x64/) until you reformat your mac.

If your problem persists after that, then feel free to re-open this ticket.

Have a good evening.
