### ISSUE TITLE
Enhancement: Logging Inputs with timings

### ISSUE THREAD

**Issue by INobody95** [KernelZechs/open-joystick-display#44]
Hello,
I’d like to humbly request / suggest a possible feature. I’d love to implement it myself, but I have no knowledge in CSS or HTML. C++ and Python is my turf.

The feature would be a simple log of Inputs and their timings. This log could be a simple csv file. Something like the following:

###
Start date and time of the first Input ( synched with serversided system time)
A (50ms duration) 
250ms (pause between inputs: system time of next input (here B) - system time of the input before (in this example A))
B (2300ms)
30ms
X (800ms)
368ms
...
###

Logging the moment the button is pressed, the duration it is pressed, and the time between two button presses circumvents the need to recognised multiple simultaneous presses. I don’t know how it works right now for the gui. Logging the time for each button separate would be fine too, if it’s how the gui works right now.

Why do I propose this feature:
I’m experimenting with LUFA (emulates Nintendo Switch Controller inputs through Arduino), trying to write macros (which I intent to make public for free) comparable to those from paid solutions (like the switch up game enhancer, which is scalped right now in America and not available in Europe). 

I could imagine there is already something like this for debugging purposes.

Having read your rules I think this feature could be useful for way more people than just myself.

**## For Feature Enhancements
Please consider the following before submitting a ticket:
- Will this enhancement benefit more than yourself?**

I think so. This feature could be used for speed runs and the practicing, which is the biggest part.
Being able to go back after practice and check where you left or gained time would be pretty useful. Furthermore records could be documented not only with a time for sections of the speed run, but boiled down to the timing of every input, which would allow to verify if it was humanly possible to archive.

**- Is it in the scope of the project or should it be directed towards another one like OBS?**

It’s in the scope of this project. It’s the only one I know that allows for displaying Nintendo switch controller inputs while playing on the switch.

- Is the enhancement you're asking for going to work-cross platform?
I don’t see why not.

Best regards,
Daniel from Germany

**Comment by KernelZechs** [comment]
@INobody95 so the long and short of it is that all you want is a downloadable log of button inputs that are synced with server time?

**Comment by INobody95** [comment]
> @INobody95 so the long and short of it is that all you want is a downloadable log of button inputs that are synced with server time?

Exactly. Do you check x times a second what is pressed or do you get feedback from the console everything something is pressed?  I can work whit whatever way is the easiest for you.
Thank you in advance

**Comment by KernelZechs** [comment]
It's very simple logic, a x ms (defined by the polling interval option) it checks for inputs and then displays them. Polling interval is there to reduce CPU usage. I could write a hook at the end of logic to sync it / log it however I feel as if there would be too much overhead but I'm happy to try and see if I can make it work. But before I do so I need you to answer below:

To write a polling/logging controller tool for your needs would be trivial to do in C (honestly a simple command line tool that hooks into the HID interface and poll it, write the buffer to a log, or memory then dump it, whatever is faster for your needs, and away you go) and *will* be way faster and more accurate than what I write (consider that this application is a visual tool at the end of the day, developed in no way to be realtime logging performant. The reasons I did not write it in C/C++ is a long one which I don't feel like diving into, but I did explore various toolkits like SDL and QT/Webkit for my solutions so I did my homework), why do you need this feature in OJD? Are you trying to relate my logging to the visual indicators on the screen? You don't need OJD to write you macro tool and likely would be a burden to what you're trying to accomplish.

I'm also having a hard trying to figure out how this helps the majority of streamers/speedrunners. Most of the LttP and Mario community (where I mostly reside) likes to have visual indicators on the screen (and truth be told, a lot of them actually prefer crotch cams over even stuff like RetroSpy and OJD for legitimacy reasons) but they are still not a 100% source of truth, logging doesn't help here because you can fake a log (see TAS input logs).

Just trying to wrap my head around what you're thinking and what you're trying to achieve with this goal. I do think the idea of an input log is kind of an interesting and wouldn't be horrible to add, but I'm afraid it will not be the sort of accuracy you're looking to accomplish.

**Comment by INobody95** [comment]
I think you are right. My programming skills are pretty rudimentary, so I stumbled over your tool and thought that if you manage to poll the inputs while playing on the Switch, it would be easy just to log those polls. But like you said, I wouldnt need the GUI perse. 
If I got this right OJDS-NX (sys-ftpd) broadcasts the actual inputs (the int values) over a request from the server PC. So I'd only need to connect to the switch and send the pollrequest every X ms and then log the response with either the time I send the pollrequest or the time I got back a response (since I only need the time between commands, not the actual time), right?
OJD would most likely just block some ressources. 

I did not think about the possibility to fake your logs. And if the demand from the communities isnt there, there is no point to add this to OJD. Was just imagining who could use this feature.

Thank you for pointing me in the right direction, let me know if you already got a concrete idea how to realise the logging in C (I got some reading to do to understand OJDS-NX fully). 
Thank you for taking your time responding to my inquire.

**Comment by KernelZechs** [comment]
No problem, I hope your project goes well. Perhaps the homebrew switch crew (such as AtlasNX) might be able to help you out with this. For the record, I'm not the maintainer for OJDS-NS, that would be my sister (https://github.com/NicholeMattera/OJDS-NX/) You could look at her code and pull what you need from that in terms of input hooking for the switch. From there, in theory, you could just modify the code to do logging instead of network broadcasting. For now, I'm going to close this ticket. Take it easy.
