### ISSUE TITLE
Bug: RetroSpy N64 input mismatch

### ISSUE THREAD

**Issue by DaviBe92** [KernelZechs/open-joystick-display#45]
Bug: RetroSpy N64 input mismatch

1. C Buttons Left and Right non Functional

- Only 12 of 14 Buttons available 

  - Buttons 12, 13 (C Left, C Right) are non existent in the Input Tester

   - Input Mapper shows correct Map

2. Analog Stick wrong range

- Range is from 0 - 1 but should be -0.5 - 0.5

Video showing the issue:
[https://youtu.be/Vy5I5SmRelM](https://youtu.be/Vy5I5SmRelM)

(Everything is working fine when using the RetroSpy software as the Frontend)

Programm Version: 2.0 - 2.8.0
OS Name:                   Microsoft Windows 10 Pro                                                                     
OS Version:                10.0.18363 N/A Build 18363 

![1](https://user-images.githubusercontent.com/44605966/77095949-ea3a5800-6a0e-11ea-831a-3c56b397c01e.jpg)
![2](https://user-images.githubusercontent.com/44605966/77095955-ead2ee80-6a0e-11ea-8971-e01221a861e9.jpg)

**Comment by KernelZechs** [comment]
@DaviBe92 did modifying the mapping fix your issues?

**Comment by DaviBe92** [comment]
No, the Profile Input Driver only shows 12 Buttons, so Buttons 12 and 13 are not being recognised.
I dont think the range of the analog stick can be remapped, can it?

**Comment by KernelZechs** [comment]
So 12 and 13 is prob. a backend driver problem I can fix. However you can tweak the directional range. I would delete the directional and use a linear trigger function. I'll have to pull out my N64 cables and see if I can replicate this analog problem. This may have been a change since when I tested this and now. 

The buttons are def. my fault since they are statically mapped, so I'll try and take some time this weekend to fix it. If I don't have my old N64 cable it may be awhile since I've been unable to get anything off of amazon because of COVID nonsense.

**Comment by DaviBe92** [comment]
Ok, no worries, stay safe :)

I was able to remap the Analog Stick to the D-Pad using Triggers and it works, but i am not able to select the  Stick as a "Trigger Button"

**Comment by KernelZechs** [comment]
I am no longer working on this project. This project will be archived. You can find more info here: http://kernelzechs.com/open-joystick-display/
