### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by dregimbal** [KernelZechs/open-joystick-display#46]
Hello, I noticed really high CPU usage while using the app on Windows. After a little debugging, i discovered it was because styles are being applied every poll, instead of just when there are changes.

I've made some modifications on a fork [here](https://github.com/dregimbal/open-joystick-display) that brought the idle usage from ~20% to ~1%, and active usage (spinning control stick, mashing buttons...etc.) from ~50% to ~15%

**Comment by KernelZechs** [comment]
@dregimbal. Thanks for doing this! Anything to add some performance gains would be welcomed while I'm moving this code to react is much appreciated. 

Can you make a PR for these changes so we can proceed? However, I noticed you turned back on HW acceleration. You can't do that. Windows OBS cannot capture the electron windows because of the chromium offscreen renderer problem. You will end up with a black screen in windows OBS using window capture. Furthermore if you're not using a compositor in Linux you can end up with artifacting in OBS, which isn't pretty.

I'm going to close this ticket, let's follow up on a proper PR. Thanks!

**Comment by dregimbal** [comment]
No worries, I made the edits for purely selfish reasons 😆 

I'll try to clean up my changes a bit (they are pretty hacky) and make a PR.

I haven't tested it on Linux, but I wasn't running into any issues recording/streaming through OBS on Windows with the acceleration enabled. Having said that, I will omit it from the changes.
