### ISSUE TITLE
(Pro Controller) OJD doesn't show button presses.

### ISSUE THREAD

**Issue by LeonLeisten** [KernelZechs/open-joystick-display#52]
Bug Report
  - Windows 10 Pro (Version: 10.0.18363 Build 18363)
  - OJD v2.8.0

I'm using a Switch Pro Controller (Bluetooth) and it works fine in other programs or games, but OJD doesn't show the button presses. Sometimes OJD showed them for a few seconds but I can't recreate it anymore. The controller is detected by the the Input Tester (see link below).

Screenshots of OJD: https://imgur.com/iJVEOno

What I'm doing:
  - I have OJD open with:
    - Theme: Nintendo Switch
    - Profile Mapping (Default): Nintendo Switch (Hacked) OJD Server NX
    - Profile Input Driver: Operating System (Chromium)
  - When I connect the controller via Bluetooth it sometimes worked for a few seconds.

I've tried to restart the program and my system but the problem is still the same.

**Comment by KernelZechs** [comment]
This is likely not related OJD but your Bluetooth driver or device. I just tested it on windows 10 (10.0.18363 N/A Build 18363) and it works fine. If OJD is not detecting it in the input tester likely it's not showing up as working in your USB game controllers tester dialog either. Can you confirm this?

**Comment by LeonLeisten** [comment]
https://imgur.com/a/bbJ2Yc2
^ If I'm using the Windows Controller Tester the inputs are not showing up but it works perfectly fine on https://html5gamepad.com (as seen in image; I'm holding the A-button and the left stick into the up-right direction).

**Comment by KernelZechs** [comment]
`OJD Server NX` I missed this portion, sorry I didn't catch it earlier. I don't support this software. This sounds like an issue with the server software. I suggest you go make a ticket over at my sister's github and not mine since she writes the server driver for the Server NX. https://github.com/NicholeMattera/OJDS-NX

**Comment by LeonLeisten** [comment]
Maybe that's a misunderstanding on my side. I just selected the mapping option that had "Nintendo Switch" in it because I'm using a Switch Pro Controller, I don't know anything about that "(Hacked) OJD Server NX" part. I just want to show my local controller and it doesn't seem to work. Did I make a mistake with the mapping or anywhere else?

Also, https://gamepadviewer.com is working, so I'm really confused why OJD isn't.

**Comment by KernelZechs** [comment]
If this is local I can help. @LeonLeisten looking at your screenshot from before, it says its on index 1. Did you try changing the player input on OJD to see if that works for you?

**Comment by LeonLeisten** [comment]
I tried it and there is no controller connected for players 2-4. The controller that is shown on Player 1 (called "Player 0 - Wireless Gamepad (Vendor: 057e Product: 2009): 16 Buttons, 10 Axes.") is the controller that I am using (it disappears when I disconnect my controller).

> https://imgur.com/a/bbJ2Yc2
> ^ If I'm using the Windows Controller Tester the inputs are not showing up
It seems that Windows does not recognize the controller, although it works in other programs and games. It is also recognized by online tools.

**Comment by KernelZechs** [comment]
I can't seem to replicate this on my end with my switch pro controller. At this point since I know this works (and I have reported users that use this controller just fine) this seems like a system configuration issue. If your windows gamepad control panel isn't working with it that is a sign something is wrong. How or why these other tools work with it doesn't make any logical sense to me since the OS needs to send those HID inputs to your game/browser/etc, but I digress, we're past application support at this point since I've verified its functionality.

For you I suggest the following:
- Ensure you don't have any other gamepad software (like joytokey) installed or some 3rd party switch controller driver. 
- Ensure your have the latest bluetooth drivers from your motherboard vendor
- Make sure something isn't wrong with the controller itself (I've had a bad pro controller in the past do stuff like you're describing)
- Try a clean install of Windows (unlikely you will do that, but I don't know what you have installed on your PC that could be causing problems.)

At this point this is all I can offer since I'm not PC tech support. If something like gamepad viewer works for you then by all means use it, but I'm at a loss as to how to help you when I can use it and others can as well.

Sorry I couldn't be of more help.
